config/routes.rb
# == Route Map
#
#   Prefix Verb   URI Pattern              Controller#Action
#     root GET    /                        cats#index
#     cats GET    /cats(.:format)          cats#index
#          POST   /cats(.:format)          cats#create
#  new_cat GET    /cats/new(.:format)      cats#new
# edit_cat GET    /cats/:id/edit(.:format) cats#edit
#      cat GET    /cats/:id(.:format)      cats#show
#          PATCH  /cats/:id(.:format)      cats#update
#          PUT    /cats/:id(.:format)      cats#update
#          DELETE /cats/:id(.:format)      cats#destroy
#

Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'cats#index'

  resources :cats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id                   :integer          not null, primary key
#  name                 :string           not null
#  age                  :integer
#  gender               :string
#  fur_color            :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  picture_file_name    :string
#  picture_content_type :string
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#

class Cat < ApplicationRecord
  has_attachment :picture, accept: [:jpg, :png, :gif]
  belongs_to :user
  validates_presence_of :name
  validates_inclusion_of :gender, in: %w(male female)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cats, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, except: [:index, :new, :create]

  def index
    @cats = current_user.cats.paginate(page: params[:page], per_page: 15)
  end

  def show
  end

  def new
    @cat = current_user.cats.new
  end

  def create
    @cat = current_user.cats.new(cat_params)
    if @cat.save
      redirect_to cat_path(@cat), success: 'Cat created!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @cat.update(cat_params)
      redirect_to cat_path(@cat), success: 'Cat updated!'
    else
      render :edit
    end
  end

  def destroy
    @cat.destroy
    redirect_to cats_path, success: 'Cat deleted!'
  end

  private
    def cat_params
      params.require(:cat).permit(:name, :age, :gender,
                                  :fur_color, :picture)
    end

    def set_cat
      @cat = current_user.cats.find(params[:id])
    end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :age])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :age])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/_form.html.erb
<%= form_for @cat do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>
  <div>
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>
  <div>
    <%= f.label :gender %>
    <%= f.select :gender, ['male', 'female'] %>
  </div>
  <div>
    <%= f.label :fur_color %>
    <%= f.text_field :fur_color %>
  </div>
  <div>
    <%= f.label :picture %>
    <%= f.attachinary_file_field :picture %>
  </div>
  <%= f.submit nil, class: 'btn btn-success' %>
<% end %>

app/views/cats/edit.html.erb
<h1> Editing Cat <%= @cat.name %></h1>

<%= render(partial: 'form') %>

app/views/cats/index.html.erb
<h1> All Cats For <%= current_user.full_name %></h1>
<hr />

<% if @cats.count >= 3 %>
  <h3 class='text-danger'>You're a crazy cat lady!</h3>
<% end %>


<div>
  <% if @cats.any? %>
    <% @cats.each do |cat| %>
      <div class='well col-sm-12 col-md-4'
        <h6><%= cat.name %></h6>
        <div>
          <%= link_to 'Show', cat_path(cat), class: 'btn' %>
        </div>
      </div>
    <% end %>
  <% else %>
    <h3>There are no cats, please create one.</h3>
  <% end %>
</div>
<div class='clearfix'></div>
<hr />
  <div class='well'>
    <%= will_paginate @cats %>
  </div>
<hr />
<%= link_to 'New Cat', new_cat_path, class: 'btn' %>--
<%= link_to 'Logout', destroy_user_session_path, method: :delete %>

app/views/cats/new.html.erb
<h1> New Cat For <%= current_user.full_name %></h1>

<%= render(partial: 'form') %>

app/views/cats/show.html.erb
<h1> <%= @cat.name %> </h1>
<% if @cat.picture? %>
  <%= cl_image_tag(@user.picture.path, {size: '125x125', crop: :fit}) %>
<% end %>

<p><%= @cat.age %></p>
<p><%= @cat.gender %></p>
<p><%= @cat.fur_color %></p>

<%= link_to 'Edit', edit_cat_path(@cat) %>
<%= link_to 'Delete', cat_path(@cat), method: :delete %>
<%= link_to 'All Cats', cats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstHerokuapp</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class='flash <%= key %>'
        <%= value %>
      </div>
    <% end %>

    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>